pull_request_templates:
  - name: âœ¨ Feature PR
    description: Add a new capability to Bolt
    file: feature_request.md

  - name: ğŸ Bug Fix PR
    description: Fix an issue or crash in the system
    file: bug_fix.md

  - name: ğŸ“ Documentation PR
    description: Make changes to the documentation only
    file: docs_only.md
